#!/bin/zsh

alias rss="newsboat"
alias iv="sxiv"
alias v="nvim"
alias q="exit"

alias ls="ls -hN --color=auto --group-directories-first"
alias ll="ls -l"
alias grep="grep --color=auto"
alias diff="diff --color=auto"
alias less="less -R"

alias syu="sudo pacman -Syu"
alias s="sudo pacman -S"
alias ss="unbuffer pacman -Ss"
alias rns="sudo pacman -Rns"
