#!/bin/zsh
HISTFILE=$XDG_CONFIG_HOME/zsh/history
HISTSIZE=10000
SAVEHIST=10000
setopt hist_ignore_all_dups hist_ignore_space
setopt extendedglob nomatch
unsetopt autocd beep notify
bindkey -v

autoload -Uz compinit
zstyle ':completion:*' menu select
compinit -d $XDG_CACHE_HOME/zsh/zcompdump-$ZSH_VERSION

function zle-keymap-select () {
    case $KEYMAP in
        vicmd) echo -ne '\e[1 q';;
        viins|main) echo -ne '\e[5 q';;
    esac
}
zle -N zle-keymap-select
zle-line-init() {
    zle -K viins
    echo -ne "\e[5 q"
}
zle -N zle-line-init
echo -ne '\e[5 q'
preexec() { echo -ne '\e[5 q' ;}

PS1='%B[%(!.%F{red}.%F{cyan})%n@%M%f %F{blue}%1~%f] %(!.#.$)%b '
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $XDG_CONFIG_HOME/zsh/aliasrc

source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh
export FZF_DEFAULT_COMMAND='fd --hidden --follow --exclude .git --exclude .cache --exclude share'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
